apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.certManagerClusterIssuer }}"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Forwarded-Proto: https";
    {{- if .Values.redirectProtocol }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.redirectProtocol | quote }}
    {{- end }}
    {{- if .Values.redirectHost }}
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.redirectHost | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if .Values.redirectUpstreamHost }}
                name: {{ .Release.Name }}--redirect
                {{- else }}
                name: {{ .Release.Name }}--frontend
                {{- end }}
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.hostname }}
        - www.{{ .Values.hostname }}
      secretName: {{ .Release.Name }}--frontend--letsencrypt-cert
---
{{- if .Values.redirectUpstreamHost }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Release.Name }}--redirect
spec:
  externalName: {{ .Values.redirectUpstreamHost | quote }}
  ports:
    - port: {{ .Values.redirectUpstreamPort }}
      name: http
  type: "ExternalName"
{{- end }}